'use client';

/**
 * AISummaryCard — Reusable AI insight card with confidence score and agent attribution.
 * Communicates intelligence and transparency across district workflows.
 */
import Card from '@mui/material/Card';
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import { useTheme, alpha } from '@mui/material/styles';

interface AISummaryCardProps {
  title?: string;
  summary: string;
  confidence?: string | number;
  agent?: string;
  action?: React.ReactNode;
}

export default function AISummaryCard({
  title = 'AI District Summary',
  summary,
  confidence = '94%',
  agent = 'Executive Briefing Agent',
  action,
}: AISummaryCardProps) {
  const theme = useTheme();

  return (
    <Card
      variant="outlined"
      sx={{
        p: 2.5,
        borderLeft: '4px solid',
        borderLeftColor: 'primary.main',
        bgcolor: alpha(theme.palette.primary.main, 0.03),
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      <Stack direction="row" alignItems="flex-start" justifyContent="space-between" spacing={2} sx={{ mb: 1.5 }}>
        <Stack direction="row" alignItems="center" spacing={1}>
          <Box
            sx={{
              width: 28,
              height: 28,
              borderRadius: 1.5,
              bgcolor: alpha(theme.palette.primary.main, 0.12),
              color: 'primary.main',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
            }}
          >
            <AutoAwesomeIcon sx={{ fontSize: 16 }} />
          </Box>
          <Typography variant="subtitle1" sx={{ fontWeight: 600, color: 'text.primary' }}>
            {title}
          </Typography>
        </Stack>

        <Stack direction="row" alignItems="center" spacing={1}>
          {confidence && (
            <Chip
              size="small"
              label={`Confidence ${confidence}`}
              sx={{
                bgcolor: alpha(theme.palette.primary.main, 0.1),
                color: 'primary.main',
                fontWeight: 600,
                fontSize: 11,
                height: 22,
              }}
            />
          )}
          {action}
        </Stack>
      </Stack>

      <Typography variant="body2" sx={{ color: 'text.primary', lineHeight: 1.6, mb: 2, fontWeight: 400 }}>
        {summary}
      </Typography>

      <Stack direction="row" alignItems="center" justifyContent="space-between" sx={{ pt: 1.5, borderTop: '1px solid', borderColor: 'divider' }}>
        <Typography variant="caption" sx={{ color: 'text.secondary', fontWeight: 500, fontSize: 11 }}>
          ✦ Generated by <Box component="span" sx={{ fontWeight: 600, color: 'text.primary' }}>{agent}</Box>
        </Typography>
        <Typography variant="caption" sx={{ color: 'text.secondary', fontSize: 11 }}>
          BigQuery ML · Gemini 2.5
        </Typography>
      </Stack>
    </Card>
  );
}
