/**
 * S13 — Reports library (docs/08 §2). Download issues signed GCS URLs once
 * svc-reports is live; demo rows show the library shape.
 */
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import Divider from '@mui/material/Divider';
import DownloadIcon from '@mui/icons-material/Download';
import HourglassEmptyIcon from '@mui/icons-material/HourglassEmpty';
import { reports } from '@/lib/demo-data';

const KIND_LABEL = { monthly: 'Monthly', outbreak: 'Outbreak post-mortem', adhoc: 'Ad hoc' } as const;

export default function ReportsPage() {
  return (
    <Box component="main" sx={{ p: { xs: 2, md: 3 }, display: 'grid', gap: 2, maxWidth: 840 }}>
      <Stack direction="row" alignItems="baseline" spacing={1.5} flexWrap="wrap">
        <Typography variant="h3">Reports</Typography>
        <Typography variant="body2" color="text.secondary">
          Generated by the Report Agent · state-review format · archived in Cloud Storage
        </Typography>
      </Stack>

      <Card>
        <Stack divider={<Divider />}>
          {reports.map((report) => (
            <Stack key={report.id} direction="row" spacing={2} alignItems="center" sx={{ p: 2 }}>
              <Stack sx={{ flex: 1, minWidth: 0 }}>
                <Typography variant="body2" sx={{ fontWeight: 600 }}>{report.title}</Typography>
                <Typography variant="caption" color="text.secondary">{report.period}</Typography>
              </Stack>
              <Chip size="small" variant="outlined" label={KIND_LABEL[report.kind]} />
              {report.status === 'available' ? (
                <Button size="small" variant="outlined" startIcon={<DownloadIcon />} disabled
                  title="Signed URL download activates with svc-reports">
                  PDF
                </Button>
              ) : (
                <Chip size="small" icon={<HourglassEmptyIcon sx={{ fontSize: 14 }} />} label="Generating" />
              )}
            </Stack>
          ))}
        </Stack>
      </Card>

      <Typography variant="caption" color="text.secondary">
        Downloads are disabled in demo mode — the PDF pipeline (Report Agent → svc-reports → signed URL)
        activates when the backend services deploy (docs/11 Sprint 9).
      </Typography>
    </Box>
  );
}
