'use client';

/**
 * Reports Library Page — Archived and generating executive healthcare reports.
 * Features document icons, semantic kind chips, download actions, and generating shimmer states.
 */
import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Chip from '@mui/material/Chip';
import Button from '@mui/material/Button';
import Divider from '@mui/material/Divider';
import DownloadIcon from '@mui/icons-material/Download';
import HourglassEmptyIcon from '@mui/icons-material/HourglassEmpty';
import PictureAsPdfOutlinedIcon from '@mui/icons-material/PictureAsPdfOutlined';
import AssessmentOutlinedIcon from '@mui/icons-material/AssessmentOutlined';
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined';
import { useTheme, alpha } from '@mui/material/styles';
import { reports, type ReportRow as Report } from '@/lib/demo-data';
import PageHeader from '@/components/PageHeader';

const KIND_LABEL: Record<Report['kind'], string> = {
  monthly: 'Monthly Compliance',
  outbreak: 'Outbreak Post-Mortem',
  adhoc: 'Ad-hoc Investigation',
};

const KIND_COLORS: Record<Report['kind'], 'primary' | 'error' | 'secondary'> = {
  monthly: 'primary',
  outbreak: 'error',
  adhoc: 'secondary',
};

const KIND_ICONS: Record<Report['kind'], typeof PictureAsPdfOutlinedIcon> = {
  monthly: AssessmentOutlinedIcon,
  outbreak: PictureAsPdfOutlinedIcon,
  adhoc: DescriptionOutlinedIcon,
};

export default function ReportsPage() {
  const theme = useTheme();

  const handleDownload = (report: Report) => {
    const dateStr = new Date().toLocaleDateString('en-IN', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });

    const content = `==================================================
              SWASTHYAOPS AI REPORT
==================================================
Report ID:     ${report.id}
Report Title:  ${report.title}
Report Period: ${report.period}
Report Kind:   ${KIND_LABEL[report.kind]}
Generated At:  ${dateStr}

--------------------------------------------------
                EXECUTIVE SUMMARY
--------------------------------------------------
This document contains the consolidated healthcare and operations metrics for District Sikar.

1. STOCK SUMMARY:
   - Primary Essential Medicine List (EDL) compliance: 92.4%
   - Critical Stockouts Reported: 2 (PHC Losal: ORS, CHC Fatehpur: Amoxicillin)
   - Stock-at-risk facilities: 7 (District average 14-day safety cover breached)

2. STAFF ATTENDANCE:
   - Clinical staff present: 84% average
   - Medical Officer presence: 91% average

3. INPATIENT CAPACITY:
   - Sanctioned beds: 462
   - Beds occupied: 344 (74.4% saturation)

--------------------------------------------------
Report generated by SwasthyaOps Report Agent.
End of Document.
==================================================`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${report.id}_report.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Box component="main" sx={{ p: { xs: 2, md: 3 }, maxWidth: 1080, mx: 'auto' }}>
      <PageHeader
        title="Reports Library & Archives"
        subtitle="Consolidated state-review documentation generated autonomously by the SwasthyaOps Report Agent. Stored securely in Cloud Storage buckets with SHA-256 tamper verification."
        badge={<Chip size="small" label={`${reports.length} Reports`} color="primary" sx={{ fontWeight: 700 }} />}
      />

      <Card sx={{ bgcolor: 'background.paper' }}>
        <Stack divider={<Divider />}>
          {reports.map((report) => {
            const Icon = KIND_ICONS[report.kind] || DescriptionOutlinedIcon;
            const isGenerating = report.status === 'generating';

            return (
              <Box
                key={report.id}
                sx={{
                  p: 2.5,
                  transition: 'all 200ms cubic-bezier(0.2, 0, 0, 1)',
                  bgcolor: isGenerating ? alpha(theme.palette.warning.main, 0.04) : 'transparent',
                  '&:hover': {
                    bgcolor: 'action.hover',
                  },
                }}
              >
                <Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} alignItems={{ xs: 'flex-start', sm: 'center' }} justifyContent="space-between">
                  <Stack direction="row" spacing={2} alignItems="center" sx={{ minWidth: 0, flex: 1 }}>
                    <Box
                      sx={{
                        width: 44,
                        height: 44,
                        borderRadius: 2,
                        bgcolor: alpha(theme.palette[KIND_COLORS[report.kind]].main, 0.1),
                        color: `${KIND_COLORS[report.kind]}.main`,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        flexShrink: 0,
                      }}
                    >
                      <Icon sx={{ fontSize: 24 }} />
                    </Box>

                    <Stack spacing={0.25} sx={{ minWidth: 0 }}>
                      <Typography variant="body1" sx={{ fontWeight: 600, color: 'text.primary' }}>
                        {report.title}
                      </Typography>
                      <Stack direction="row" alignItems="center" spacing={1} flexWrap="wrap">
                        <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 500 }}>
                          Period: {report.period}
                        </Typography>
                        <Typography variant="caption" color="text.disabled">
                          ·
                        </Typography>
                        <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>
                          ID: {report.id}
                        </Typography>
                      </Stack>
                    </Stack>
                  </Stack>

                  <Stack direction="row" alignItems="center" spacing={1.5} sx={{ alignSelf: { xs: 'flex-end', sm: 'center' } }}>
                    <Chip
                      size="small"
                      label={KIND_LABEL[report.kind]}
                      color={KIND_COLORS[report.kind]}
                      variant="outlined"
                      sx={{ fontWeight: 600, height: 24 }}
                    />

                    {report.status === 'available' ? (
                      <Button
                        size="small"
                        variant="contained"
                        startIcon={<DownloadIcon />}
                        onClick={() => handleDownload(report)}
                        sx={{ borderRadius: 999, fontWeight: 600, px: 2.5 }}
                      >
                        Download
                      </Button>
                    ) : (
                      <Chip
                        size="small"
                        icon={<HourglassEmptyIcon sx={{ fontSize: 14 }} />}
                        label="Generating..."
                        color="warning"
                        sx={{
                          fontWeight: 700,
                          px: 1,
                          animation: 'pulse-shimmer 1.5s infinite ease-in-out',
                          '@keyframes pulse-shimmer': {
                            '0%': { opacity: 0.6 },
                            '50%': { opacity: 1 },
                            '100%': { opacity: 0.6 },
                          },
                        }}
                      />
                    )}
                  </Stack>
                </Stack>
              </Box>
            );
          })}
        </Stack>
      </Card>

      <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 2, textAlign: 'center' }}>
        ✦ Generated documents are signed with cryptographic timestamps for audit readiness across state health directorates.
      </Typography>
    </Box>
  );
}
