# SLOs and alert policies (docs/02_TRD.md §9, §15). Dashboards JSON kept alongside.

resource "google_monitoring_uptime_check_config" "api" {
  count        = var.enable_edge ? 1 : 0 # probes the custom domain; meaningless without it
  display_name = "svc-api /healthz"
  timeout      = "10s"
  period       = "60s"
  http_check {
    path         = "/healthz"
    use_ssl      = true
    validate_ssl = true
  }
  monitored_resource {
    type   = "uptime_url"
    labels = { project_id = var.project_id, host = "api.${var.env}.${var.domain}" }
  }
}

locals {
  alert_policies = {
    dlq-nonempty = {
      display = "Pub/Sub DLQ non-empty 10 min"
      filter  = "resource.type=\"pubsub_topic\" AND resource.labels.topic_id=monitoring.regex.full_match(\".*\\\\.dlq\") AND metric.type=\"pubsub.googleapis.com/topic/send_message_operation_count\""
      threshold = 0
      duration  = "600s"
      comparison = "COMPARISON_GT"
    }
    api-5xx = {
      display = "svc-api 5xx ratio > 0.5%"
      filter  = "resource.type=\"cloud_run_revision\" AND resource.labels.service_name=\"svc-api\" AND metric.type=\"run.googleapis.com/request_count\" AND metric.labels.response_code_class=\"5xx\""
      threshold = 0.005
      duration  = "300s"
      comparison = "COMPARISON_GT"
    }
    briefing-missed = {
      display = "Daily briefing not generated by 07:15 IST"
      filter  = "metric.type=\"logging.googleapis.com/user/briefing_generated\" AND resource.type=\"cloud_run_revision\""
      threshold = 1
      duration  = "0s"
      comparison = "COMPARISON_LT"
    }
  }
}

resource "google_monitoring_alert_policy" "policies" {
  for_each     = local.alert_policies
  display_name = each.value.display
  combiner     = "OR"

  conditions {
    display_name = each.value.display
    condition_threshold {
      filter          = each.value.filter
      comparison      = each.value.comparison
      threshold_value = each.value.threshold
      duration        = each.value.duration
      aggregations {
        alignment_period   = "300s"
        per_series_aligner = "ALIGN_RATE"
      }
    }
  }

  notification_channels = var.alert_notification_channels
  severity              = "ERROR"
}

# Log-based metric backing the briefing SLO (svc-reports logs briefing_generated)
resource "google_logging_metric" "briefing_generated" {
  name   = "briefing_generated"
  filter = "resource.type=\"cloud_run_revision\" AND jsonPayload.event=\"briefing_generated\""
}

# Budget alerts (docs/10 §10) are configured at billing-account scope outside this
# project-scoped module; thresholds 50/80/100% documented there.
